### ISSUE TITLE
Direct v1.0 tracking

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/direct#152]
- [x] Improve documentation
  - [x] How to add another dataset
  - [x] How to add another sampling mask
  - [x] How to run training/inference
- [x] Add test coverage (#153)
- [x] Reduce pylint warnings 
- [x] Update versions of used libraries

**Comment by jonasteuwen** [comment]
#153 adds a coverage check, but it should also add this to any PR. Look into it why it doesn't happen right now.

**Comment by jonasteuwen** [comment]
Release candidate branched off in https://github.com/directgroup/direct/tree/v1.0.0-rc
