### ISSUE TITLE
v2.1.0 tracking

### ISSUE THREAD

**Issue by georgeyiasemis** [NKI-AI/direct#281]
- [x] CMRxRecon 2023 yaml files (#274)
- [x] SSL functionality (#277)
- [x] JSSL functionality and experiments (#277, #278) 
- [x] Rescale, Pad, Compress coil transforms (#279)
- [ ] Non-static maskers (#280)
- [x] Bump workflows py version to 3.9 and 3.10 (#279)
